### PR TITLE
chore: upgrade to latest contracts

### PR DESCRIPTION
**Pull request by joepegler**
## PR-Codex overview
This PR focuses on updating the `Nexus` and related components, improving contract definitions, and refining testing processes. It includes changes to dependencies, contract ABIs, and introduces a new GitHub workflow for PR linting.

### Detailed summary
- Removed `EIP1271Abi` export from `src/sdk/__contracts/abi/index.ts`.
- Updated `nexus` dependency in `package.json`.
- Changed `chainName` in `scripts/fetch:deployment.ts`.
- Renamed `Bootstrap` to `NexusBootstrap` in `src/sdk/__contracts/abi/K1ValidatorFactoryAbi.ts`.
- Updated `NEXUS_DOMAIN_NAME` to lowercase and version in `src/sdk/account/utils/Constants.ts`.
- Added a new GitHub workflow for PR linting.
- Refined contract ABI definitions, including new events and functions in `NexusAbi.ts` and `K1ValidatorAbi.ts`.
- Modified test files to reflect updated contract addresses and ensure compatibility with changes.
- Introduced `getAccountMeta` function in `src/sdk/account/utils/Utils.ts`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by livingrockrises** [comment]
the contracts are from which branch of nexus?
and any updates from smart session?

**Comment by joepegler** [comment]
> the contracts are from which branch of nexus? and any updates from smart session?

https://github.com/bcnmy/sdk/pull/60/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R101

**Comment by joepegler** [comment]
WE haven't been keeping up to date with smart sessions have we, as we import ss using the bytecode taken from an old base sepolia deployment.

**Comment by livingrockrises** [comment]
> WE haven't been keeping up to date with smart sessions have we, as we import ss using the bytecode taken from an old base sepolia deployment.

yeah, I replaced with address taken from module sdk and my tests broke down.

one issue I had faced was not attesting in mock registry but current run seemed like a different issue. for former I have deployed my version to bypass registry. way to do it with is attesting
"if you have problems with the registry then you can mock attest to modules you’re using: https://docs.rhinestone.wtf/module-registry/usage/mock-attestation"

**Comment by livingrockrises** [comment]
> > WE haven't been keeping up to date with smart sessions have we, as we import ss using the bytecode taken from an old base sepolia deployment.
> 
> yeah, I replaced with address taken from module sdk and my tests broke down.
> 
> one issue I had faced was not attesting in mock registry but current run seemed like a different issue. for former I have deployed my version to bypass registry. way to do it with is attesting "if you have problems with the registry then you can mock attest to modules you’re using: https://docs.rhinestone.wtf/module-registry/usage/mock-attestation"

check the whole thread in rhinestone channel. there is no specific branch yet to keep track of at the mo

**Pull request merged**
